version: '3'
services:
  mailer:
    command: 'npm run start-dev'
    links:
      - messenger
    volumes:
      - ./:/app
  api:
    image: boggs/api
    links:
      - messenger
    ports:
      - 8888:80
    env_file:
      - .env
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
  messenger:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - messenger-data:/var/lib/rabbitmq
volumes:
  messenger-data:
